# -*- coding: utf-8 -*-
"""sqlite_dataexploration.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11eNC3yhRK5Trh7y8FYy4ZQVDVVaD4y_q
"""

import pandas as pd

import sqlite3

conn = sqlite3.connect('healthcare.db')
state_conn = sqlite3.connect('state_le.db')

df = pd.read_csv('https://data.cdc.gov/resource/b666-c5v5.csv')

df

df.to_sql('prescription_drug_use', conn, if_exists='replace', index=False)

pd.read_sql_query("SELECT * FROM healthcare_data LIMIT 20;", conn)

query = 'SELECT * FROM healthcare_data WHERE subgroup = \'Younger than 18 years\''

query = 'SELECT * FROM healthcare_data WHERE subgroup = \'Younger than 18 years\''
result_query1 = pd.read_sql(query, conn)
print(result_query1)

query_2 = 'SELECT COUNT (*) FROM healthcare_data WHERE time_period = \'2017-2020\''
result_query2 = pd.read_sql(query_2, conn)
print(result_query2)

query_3 = 'SELECT SUBGROUP, AVG(ESTIMATE) as avg_estimate FROM healthcare_data WHERE SUBGROUP = \'Female\'GROUP BY SUBGROUP'
result_query3 = pd.read_sql(query_3, conn)
print(result_query3)

df = pd.read_csv('https://data.cdc.gov/resource/it4f-frdc.csv')
df.to_sql('state_le_db', state_conn, if_exists='replace', index=False)
print(df)

query_4 = 'SELECT area, sex, leb FROM state_le_db WHERE Sex = \'Female\' ORDER BY leb DESC LIMIT 5'
result_query4 = pd.read_sql(query_4, state_conn)
print(result_query4)